import ViewGeneral from './ViewGeneral.vue';
import ViewSurveys from './ViewSurveys.vue';
import ViewQuotes from './ViewQuotes.vue';
import ViewDocuments from './ViewDocuments.vue';
import ViewProspects from './ViewProspects.vue';
import ViewReservas from './ViewReservas.vue';
import ViewContract from './ViewContract.vue';
import ViewContacts from './ViewContacts.vue';
import ViewProyects from './ViewProyects.vue';
import ViewEntregas from './view.entregas.vue';
import ViewSurveysConducted from './ViewSurveysConducted.vue';
export { ViewGeneral, ViewSurveys,ViewContacts, ViewQuotes, ViewDocuments,ViewSurveysConducted,ViewProspects ,ViewReservas,ViewContract,ViewProyects,ViewEntregas};
